name: alphagoing
description: "alphagoing"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.3
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  intl: ^0.19.0
  dio: ^5.6.0
  logger: ^2.4.0
  injectable: ^2.4.4
  collection: ^1.18.0
  fluttertoast: ^8.2.8
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  http_parser: ^4.0.2
  flutter_slidable: ^3.1.2
  easy_debounce: ^2.0.3
  daum_postcode_search: ^0.0.2
  daum_postcode_view: ^0.1.2
  bottom_sheet: ^4.0.4
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.0
  fl_chart: ^0.70.1
  appsflyer_sdk: ^6.15.1
  firebase_core: ^3.8.1
  sign_in_with_apple: ^6.1.4
  kakao_flutter_sdk_user: ^1.9.6
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  json_serializable: ^6.8.0
  go_router_builder: ^2.7.1
  freezed: ^2.5.2
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.otf
          weight: 800

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/img_splash.png

  android_12:
    image: assets/images/img_splash.png
    icon_background_color: "#ffffff"