// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8DzCu9BuCAcmdZQptPGqNxX2YB9bszv4',
    appId: '1:860919547827:web:ae1e440939fdc378712dc6',
    messagingSenderId: '860919547827',
    projectId: 'alphagoing-d744e',
    authDomain: 'alphagoing-d744e.firebaseapp.com',
    storageBucket: 'alphagoing-d744e.firebasestorage.app',
    measurementId: 'G-D5FV38D89E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFr-GIraPWkwtuID8cGCCNrB68bVolGTc',
    appId: '1:143509149908:android:5799168a75ff49fab18341',
    messagingSenderId: '143509149908',
    projectId: 'hururup-app',
    storageBucket: 'hururup-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLvChpg1A7Hj07CFYynpbNp5vfImm8zm0',
    appId: '1:143509149908:ios:ff86fd473014de00b18341',
    messagingSenderId: '143509149908',
    projectId: 'hururup-app',
    storageBucket: 'hururup-app.firebasestorage.app',
    androidClientId: '143509149908-89qt15idkjruat2clluntq8tqhbd400t.apps.googleusercontent.com',
    iosClientId: '143509149908-opoq1rnrj9ch7ock54rc9efao5251fjd.apps.googleusercontent.com',
    iosBundleId: 'com.hururup.cupping',
  );

}